/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSubscribeRouteImport } from './routes/api/subscribe'
import { Route as ApiDailyReminderRouteImport } from './routes/api/daily-reminder'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubscribeRoute = ApiSubscribeRouteImport.update({
  id: '/api/subscribe',
  path: '/api/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDailyReminderRoute = ApiDailyReminderRouteImport.update({
  id: '/api/daily-reminder',
  path: '/api/daily-reminder',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/daily-reminder': typeof ApiDailyReminderRoute
  '/api/subscribe': typeof ApiSubscribeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/daily-reminder': typeof ApiDailyReminderRoute
  '/api/subscribe': typeof ApiSubscribeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/daily-reminder': typeof ApiDailyReminderRoute
  '/api/subscribe': typeof ApiSubscribeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/daily-reminder' | '/api/subscribe'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/daily-reminder' | '/api/subscribe'
  id: '__root__' | '/' | '/api/daily-reminder' | '/api/subscribe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiDailyReminderRoute: typeof ApiDailyReminderRoute
  ApiSubscribeRoute: typeof ApiSubscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subscribe': {
      id: '/api/subscribe'
      path: '/api/subscribe'
      fullPath: '/api/subscribe'
      preLoaderRoute: typeof ApiSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/daily-reminder': {
      id: '/api/daily-reminder'
      path: '/api/daily-reminder'
      fullPath: '/api/daily-reminder'
      preLoaderRoute: typeof ApiDailyReminderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiDailyReminderRoute: ApiDailyReminderRoute,
  ApiSubscribeRoute: ApiSubscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
