/* Daily puzzles from #287 (2026-10-14) on, GENERATED by
 * scripts/gen-dailies.mjs. Add more with `node scripts/gen-dailies.mjs --add N`.
 *
 * ⚠ APPEND ONLY. Each line IS a day (the comment says which). Editing,
 * reordering or regenerating a line changes a day that may already have been
 * played, and saved games restore by puzzle number with exact block positions.
 * Easy = 2 words, Medium = 3, Hard = 4; Saturday is the hard one. */
export const DAILY_EXTENSION: string[][] = [
  ["OATS", "HERD", "HOOF"], // #287 Wed 2026-10-14
  ["FILM", "NAIL", "GALE"], // #288 Thu 2026-10-15
  ["FOGGY", "WELL", "EBB"], // #289 Fri 2026-10-16
  ["GUY", "CAR", "RUB", "PAY"], // #290 Sat 2026-10-17
  ["DYNAMO", "TOFFEE"], // #291 Sun 2026-10-18
  ["GIRAFFE", "OTTER"], // #292 Mon 2026-10-19
  ["GOGGLES", "SWORD"], // #293 Tue 2026-10-20
  ["TORCH", "KIWI", "PEG"], // #294 Wed 2026-10-21
  ["MOCHA", "MOSS", "FLU"], // #295 Thu 2026-10-22
  ["FLUTE", "ROBE", "COO"], // #296 Fri 2026-10-23
  ["ELM", "SUM", "MAX", "JAY"], // #297 Sat 2026-10-24
  ["SPRUCE", "QUIVER"], // #298 Sun 2026-10-25
  ["VORTEX", "RABBIT"], // #299 Mon 2026-10-26
  ["CHOWDER", "FROST"], // #300 Tue 2026-10-27
  ["DOCK", "FARM", "OBOE"], // #301 Wed 2026-10-28
  ["CHIMP", "WAXY", "HOG"], // #302 Thu 2026-10-29
  ["TILE", "BEAM", "WING"], // #303 Fri 2026-10-30
  ["RAT", "BYE", "LID", "FRY"], // #304 Sat 2026-10-31
  ["ZIGZAG", "BAKERY"], // #305 Sun 2026-11-01
  ["GEYSER", "BARLEY"], // #306 Mon 2026-11-02
  ["BOBCAT", "ENGINE"], // #307 Tue 2026-11-03
  ["BUMPY", "ZANY", "YEN"], // #308 Wed 2026-11-04
  ["JOKER", "FOXY", "TRY"], // #309 Thu 2026-11-05
  ["BRICK", "BOXY", "SIP"], // #310 Fri 2026-11-06
  ["BOG", "NEW", "VOW", "WAD"], // #311 Sat 2026-11-07
  ["CYMBAL", "JACKAL"], // #312 Sun 2026-11-08
  ["SCROLL", "FINGER"], // #313 Mon 2026-11-09
  ["HALIBUT", "GUAVA"], // #314 Tue 2026-11-10
  ["PIER", "SNOW", "FORT"], // #315 Wed 2026-11-11
  ["CRUMB", "TUSK", "ELK"], // #316 Thu 2026-11-12
  ["PASTA", "LUTE", "YIP"], // #317 Fri 2026-11-13
  ["TWO", "SOD", "TOP", "ORE"], // #318 Sat 2026-11-14
  ["AVENUE", "KNIGHT"], // #319 Sun 2026-11-15
  ["POPCORN", "ARROW"], // #320 Mon 2026-11-16
  ["MASCOT", "FUNGUS"], // #321 Tue 2026-11-17
  ["MANOR", "SILO", "BUD"], // #322 Wed 2026-11-18
  ["GATE", "TIDE", "FLEA"], // #323 Thu 2026-11-19
  ["SHELL", "HOSE", "YES"], // #324 Fri 2026-11-20
  ["RIM", "MIX", "INN", "SLY"], // #325 Sat 2026-11-21
  ["FUNNEL", "LOCKER"], // #326 Sun 2026-11-22
  ["WETSUIT", "LINEN"], // #327 Mon 2026-11-23
  ["SKEWER", "STATUE"], // #328 Tue 2026-11-24
  ["RUBY", "VEIL", "JUKE"], // #329 Wed 2026-11-25
  ["CHILI", "KELP", "ART"], // #330 Thu 2026-11-26
  ["CABIN", "VINE", "FUN"], // #331 Fri 2026-11-27
  ["GAP", "DIG", "CRY", "COG"], // #332 Sat 2026-11-28
  ["GALLEY", "PENCIL"], // #333 Sun 2026-11-29
  ["STREAM", "WOMBAT"], // #334 Mon 2026-11-30
  ["TIMBER", "KENNEL"], // #335 Tue 2026-12-01
  ["QUAIL", "COAL", "JUT"], // #336 Wed 2026-12-02
  ["THORN", "TOGA", "JOB"], // #337 Thu 2026-12-03
  ["MACAW", "FOAM", "MOB"], // #338 Fri 2026-12-04
  ["WOO", "BAG", "SET", "POP"], // #339 Sat 2026-12-05
  ["GAZELLE", "BLOOM"], // #340 Sun 2026-12-06
  ["KEYPAD", "BRIDGE"], // #341 Mon 2026-12-07
  ["DOORWAY", "STRAW"], // #342 Tue 2026-12-08
  ["WAFER", "BUZZ", "HUG"], // #343 Wed 2026-12-09
  ["BULB", "WREN", "LAKE"], // #344 Thu 2026-12-10
  ["KAYAK", "BARN", "SAD"], // #345 Fri 2026-12-11
  ["ORB", "SHY", "PAL", "SIX"], // #346 Sat 2026-12-12
  ["ZINNIA", "PUFFIN"], // #347 Sun 2026-12-13
  ["WAXWING", "RIVER"], // #348 Mon 2026-12-14
  ["BURGER", "COSMOS"], // #349 Tue 2026-12-15
  ["BOOTH", "BATH", "BUY"], // #350 Wed 2026-12-16
  ["ROOT", "FAWN", "CARD"], // #351 Thu 2026-12-17
  ["QUILT", "ROOF", "OWE"], // #352 Fri 2026-12-18
  ["AWL", "VEX", "PAY", "HOP"], // #353 Sat 2026-12-19
  ["PADDLE", "MUFFIN"], // #354 Sun 2026-12-20
  ["BUCKLE", "CHERRY"], // #355 Mon 2026-12-21
  ["SHERBET", "SIREN"], // #356 Tue 2026-12-22
  ["PLAID", "SPUD", "ARK"], // #357 Wed 2026-12-23
  ["STEW", "JEEP", "BOOK"], // #358 Thu 2026-12-24
  ["HOOP", "DUSK", "DECK"], // #359 Fri 2026-12-25
  ["ZAG", "OLD", "SUM", "DOT"], // #360 Sat 2026-12-26
  ["KINGPIN", "HOUND"], // #361 Sun 2026-12-27
  ["ICICLE", "SWIVEL"], // #362 Mon 2026-12-28
  ["COCONUT", "SQUID"], // #363 Tue 2026-12-29
  ["MOLE", "WELL", "OBOE"], // #364 Wed 2026-12-30
  ["CALF", "POOL", "CLAW"], // #365 Thu 2026-12-31
  ["GUPPY", "ZEST", "BOO"], // #366 Fri 2027-01-01
  ["RAW", "WOW", "WET", "ONE"], // #367 Sat 2027-01-02
  ["PASTRY", "GROTTO"], // #368 Sun 2027-01-03
  ["RUBBLE", "KIMONO"], // #369 Mon 2027-01-04
  ["OYSTER", "VIKING"], // #370 Tue 2027-01-05
  ["SCOUT", "COMB", "FIB"], // #371 Wed 2027-01-06
  ["FUDGE", "GOWN", "MAX"], // #372 Thu 2027-01-07
  ["STOVE", "HALO", "OUT"], // #373 Fri 2027-01-08
  ["BIN", "IMP", "ODE", "TRY"], // #374 Sat 2027-01-09
  ["BLAZER", "SQUAWK"], // #375 Sun 2027-01-10
  ["CABBAGE", "ORBIT"], // #376 Mon 2027-01-11
  ["TINSEL", "BEETLE"], // #377 Tue 2027-01-12
  ["LOFT", "JOEY", "KILT"], // #378 Wed 2027-01-13
  ["ROBIN", "DOLL", "HOT"], // #379 Thu 2027-01-14
  ["HORSE", "VEST", "COD"], // #380 Fri 2027-01-15
  ["TEN", "FAR", "FRY", "WIZ"], // #381 Sat 2027-01-16
  ["CARROT", "BEAKER"], // #382 Sun 2027-01-17
  ["PICCOLO", "AMBER"], // #383 Mon 2027-01-18
  ["FREIGHT", "SLOTH"], // #384 Tue 2027-01-19
  ["FOXY", "BOXY", "FIZZ"], // #385 Wed 2027-01-20
  ["CUBE", "TUSK", "FIRE"], // #386 Thu 2027-01-21
  ["KAZOO", "TOWN", "RIM"], // #387 Fri 2027-01-22
  ["JUG", "GOO", "AIR", "BUD"], // #388 Sat 2027-01-23
  ["VIOLIN", "HEARTH"], // #389 Sun 2027-01-24
  ["SAFFRON", "SWORD"], // #390 Mon 2027-01-25
  ["PEBBLE", "GADGET"], // #391 Tue 2027-01-26
  ["ZESTY", "DIME", "PUN"], // #392 Wed 2027-01-27
  ["BULL", "TILE", "YETI"], // #393 Thu 2027-01-28
  ["HILL", "FUEL", "JOLT"], // #394 Fri 2027-01-29
  ["BOP", "EWE", "CRY", "TOP"], // #395 Sat 2027-01-30
  ["HAMMOCK", "CANOE"], // #396 Sun 2027-01-31
  ["TURTLE", "BUZZER"], // #397 Mon 2027-02-01
  ["GLIDER", "FLURRY"], // #398 Tue 2027-02-02
  ["SKIFF", "FILM", "PEP"], // #399 Wed 2027-02-03
  ["LANCE", "WAXY", "SLY"], // #400 Thu 2027-02-04
  ["WING", "KELP", "RUBY"], // #401 Fri 2027-02-05
  ["JOB", "SET", "ART", "RUB"], // #402 Sat 2027-02-06
  ["WEATHER", "IVORY"], // #403 Sun 2027-02-07
  ["BREEZY", "NOODLE"], // #404 Mon 2027-02-08
  ["REFLEX", "SHAKER"], // #405 Tue 2027-02-09
  ["KOALA", "FORT", "WAD"], // #406 Wed 2027-02-10
  ["BRICK", "JUKE", "SHY"], // #407 Thu 2027-02-11
  ["RIVER", "CLUB", "YET"], // #408 Fri 2027-02-12
  ["BIT", "LOW", "ROE", "DIG"], // #409 Sat 2027-02-13
  ["SAWMILL", "SNAIL"], // #410 Sun 2027-02-14
  ["TOMCAT", "DINGHY"], // #411 Mon 2027-02-15
  ["TURBINE", "BANJO"], // #412 Tue 2027-02-16
  ["LUTE", "COZY", "REEF"], // #413 Wed 2027-02-17
  ["REED", "KIWI", "CORD"], // #414 Thu 2027-02-18
  ["PERCH", "PLOW", "HUG"], // #415 Fri 2027-02-19
  ["HUM", "WAY", "ELK", "SAD"], // #416 Sat 2027-02-20
  ["FERRET", "EMPIRE"], // #417 Sun 2027-02-21
  ["JALOPY", "CRADLE"], // #418 Mon 2027-02-22
  ["PUMPKIN", "PANSY"], // #419 Tue 2027-02-23
  ["GOOSE", "GULL", "SEW"], // #420 Wed 2027-02-24
  ["WHISK", "MANE", "ZIG"], // #421 Thu 2027-02-25
  ["CART", "LAZY", "COAL"], // #422 Fri 2027-02-26
  ["VEX", "MOW", "RAG", "KEG"], // #423 Sat 2027-02-27
  ["CAPSULE", "LUMPY"], // #424 Sun 2027-02-28
  ["SANDBOX", "SHIRT"], // #425 Mon 2027-03-01
  ["BOUQUET", "BOOTH"], // #426 Tue 2027-03-02
  ["MACAW", "LAWN", "INN"], // #427 Wed 2027-03-03
  ["HOSE", "BUZZ", "ZANY"], // #428 Thu 2027-03-04
  ["CABLE", "PEAK", "HUE"], // #429 Fri 2027-03-05
  ["WET", "GUY", "ORE", "TOT"], // #430 Sat 2027-03-06
  ["FRIDGE", "HARBOR"], // #431 Sun 2027-03-07
  ["MONARCH", "KEBAB"], // #432 Mon 2027-03-08
  ["WAFFLE", "VOYAGE"], // #433 Tue 2027-03-09
  ["CLAW", "SAGE", "FLAX"], // #434 Wed 2027-03-10
  ["SPICE", "CURL", "SAX"], // #435 Thu 2027-03-11
  ["TRUCK", "ROBE", "MIX"], // #436 Fri 2027-03-12
  ["OLD", "PAY", "SOW", "ELM"], // #437 Sat 2027-03-13
  ["FREEZE", "CARAFE"], // #438 Sun 2027-03-14
  ["COBWEB", "TARGET"], // #439 Mon 2027-03-15
  ["BONFIRE", "PUPPY"], // #440 Tue 2027-03-16
  ["CHILI", "FLEA", "HOG"], // #441 Wed 2027-03-17
  ["PLAID", "JINX", "RIP"], // #442 Thu 2027-03-18
  ["HELM", "OVAL", "SILO"], // #443 Fri 2027-03-19
  ["YAP", "SUM", "AWE", "BYE"], // #444 Sat 2027-03-20
  ["CANTEEN", "FERRY"], // #445 Sun 2027-03-21
  ["COMPASS", "GUPPY"], // #446 Mon 2027-03-22
  ["BLOSSOM", "POLKA"], // #447 Tue 2027-03-23
  ["PUMA", "COMB", "COVE"], // #448 Wed 2027-03-24
  ["MARSH", "VINE", "BIN"], // #449 Thu 2027-03-25
  ["FIRE", "SEED", "HERD"], // #450 Fri 2027-03-26
  ["GAP", "BOG", "PEW", "KIN"], // #451 Sat 2027-03-27
  ["SUBWAY", "MUSSEL"], // #452 Sun 2027-03-28
  ["TERMITE", "BEECH"], // #453 Mon 2027-03-29
  ["JAVELIN", "SLOTH"], // #454 Tue 2027-03-30
  ["JAZZY", "PIER", "YIP"], // #455 Wed 2027-03-31
  ["DAISY", "SALT", "HOT"], // #456 Thu 2027-04-01
  ["CAMP", "PAWN", "DOCK"], // #457 Fri 2027-04-02
  ["JUG", "FUN", "JAY", "COY"], // #458 Sat 2027-04-03
  ["MAGPIE", "WHIMSY"], // #459 Sun 2027-04-04
  ["JUMBLE", "CRUISE"], // #460 Mon 2027-04-05
  ["BANQUET", "KAYAK"], // #461 Tue 2027-04-06
  ["POPPY", "BULL", "SIT"], // #462 Wed 2027-04-07
  ["POOL", "FIZZ", "LOOM"], // #463 Thu 2027-04-08
  ["CHIVE", "LAMB", "BED"], // #464 Fri 2027-04-09
  ["NOD", "PRO", "DAY", "TAG"], // #465 Sat 2027-04-10
  ["RIDDLE", "BRONCO"], // #466 Sun 2027-04-11
  ["ZEPHYR", "BANYAN"], // #467 Mon 2027-04-12
  ["MARLIN", "BUBBLE"], // #468 Tue 2027-04-13
  ["ZEST", "CONE", "LACE"], // #469 Wed 2027-04-14
  ["TRAY", "CARD", "FARM"], // #470 Thu 2027-04-15
  ["MAZE", "DOME", "CAPE"], // #471 Fri 2027-04-16
  ["MAX", "OAT", "BUS", "ORB"], // #472 Sat 2027-04-17
  ["PARKWAY", "CRUMB"], // #473 Sun 2027-04-18
  ["TORNADO", "BANJO"], // #474 Mon 2027-04-19
  ["CEMENT", "FIDDLE"], // #475 Tue 2027-04-20
  ["CABIN", "WAVY", "WRY"], // #476 Wed 2027-04-21
  ["BIRD", "LAKE", "HILL"], // #477 Thu 2027-04-22
  ["YODEL", "ROOF", "HOP"], // #478 Fri 2027-04-23
  ["MOM", "ELK", "GOO", "DOT"], // #479 Sat 2027-04-24
  ["FLIGHT", "SQUASH"], // #480 Sun 2027-04-25
  ["ZENITH", "CHALET"], // #481 Mon 2027-04-26
  ["FROLIC", "TOMATO"], // #482 Tue 2027-04-27
  ["YUCCA", "FOAM", "ARK"], // #483 Wed 2027-04-28
  ["SQUID", "LILY", "ARC"], // #484 Thu 2027-04-29
  ["RHINO", "ALOE", "VEX"], // #485 Fri 2027-04-30
  ["YET", "EBB", "LAD", "MOW"], // #486 Sat 2027-05-01
  ["FROSTY", "MAMMAL"], // #487 Sun 2027-05-02
  ["PADDOCK", "CURRY"], // #488 Mon 2027-05-03
  ["KNUCKLE", "FLUTE"], // #489 Tue 2027-05-04
  ["PATIO", "RAKE", "COO"], // #490 Wed 2027-05-05
  ["HUSK", "ROOT", "DUSK"], // #491 Thu 2027-05-06
  ["CALF", "BULB", "PALM"], // #492 Fri 2027-05-07
  ["PEP", "WET", "OAR", "WAD"], // #493 Sat 2027-05-08
  ["VELVET", "SHIELD"], // #494 Sun 2027-05-09
  ["TWISTER", "HOTEL"], // #495 Mon 2027-05-10
  ["HARVEST", "HERON"], // #496 Tue 2027-05-11
  ["TIDE", "GULL", "CLUB"], // #497 Wed 2027-05-12
  ["COBRA", "GATE", "OUT"], // #498 Thu 2027-05-13
  ["FOGGY", "ARCH", "HUG"], // #499 Fri 2027-05-14
  ["BAR", "LID", "RED", "DIM"], // #500 Sat 2027-05-15
  ["RAVIOLI", "PRISM"], // #501 Sun 2027-05-16
  ["FLAGON", "DONKEY"], // #502 Mon 2027-05-17
  ["CELERY", "BOTTLE"], // #503 Tue 2027-05-18
  ["ROBOT", "OXEN", "TOT"], // #504 Wed 2027-05-19
  ["ZIPPY", "COZY", "WOW"], // #505 Thu 2027-05-20
  ["MOCHA", "FOAL", "ODD"], // #506 Fri 2027-05-21
  ["LAW", "FRY", "SLY", "PAW"], // #507 Sat 2027-05-22
  ["LIQUID", "WICKER"], // #508 Sun 2027-05-23
  ["FLUFFY", "FLORAL"], // #509 Mon 2027-05-24
  ["YELLOW", "BEANIE"], // #510 Tue 2027-05-25
  ["LODGE", "STEW", "SIP"], // #511 Wed 2027-05-26
  ["RODEO", "HAZY", "ART"], // #512 Thu 2027-05-27
  ["LOTUS", "WALL", "MOB"], // #513 Fri 2027-05-28
  ["SAX", "GAS", "JOY", "ZAG"], // #514 Sat 2027-05-29
  ["WEEVIL", "DOMINO"], // #515 Sun 2027-05-30
  ["JUKEBOX", "LEMUR"], // #516 Mon 2027-05-31
  ["HAMSTER", "BLOOM"], // #517 Tue 2027-06-01
  ["HINGE", "SAGE", "JOB"], // #518 Wed 2027-06-02
  ["STORK", "BARN", "RAG"], // #519 Thu 2027-06-03
  ["PEACH", "YETI", "DIG"], // #520 Fri 2027-06-04
  ["JAY", "COD", "YEN", "SOD"], // #521 Sat 2027-06-05
  ["MANTIS", "BUNDLE"], // #522 Sun 2027-06-06
  ["LAGOON", "BOXCAR"], // #523 Mon 2027-06-07
  ["IGUANA", "DUFFEL"], // #524 Tue 2027-06-08
  ["JUICE", "CUBE", "DRY"], // #525 Wed 2027-06-09
  ["TRUCK", "SPUD", "RIM"], // #526 Thu 2027-06-10
  ["COUCH", "PAWN", "OLD"], // #527 Fri 2027-06-11
  ["ASH", "IMP", "BOP", "COG"], // #528 Sat 2027-06-12
  ["SUNDIAL", "DAISY"], // #529 Sun 2027-06-13
  ["LENTIL", "GERBIL"], // #530 Mon 2027-06-14
  ["WHIPPET", "TORCH"], // #531 Tue 2027-06-15
  ["CLOWN", "CHIN", "FEZ"], // #532 Wed 2027-06-16
  ["EMBER", "FAWN", "SIX"], // #533 Thu 2027-06-17
  ["MOOSE", "FUEL", "ORE"], // #534 Fri 2027-06-18
  ["POT", "AWE", "RAW", "OAT"], // #535 Sat 2027-06-19
  ["BISCUIT", "QUILL"], // #536 Sun 2027-06-20
  ["TADPOLE", "VAULT"], // #537 Mon 2027-06-21
  ["AVOCADO", "DRAKE"], // #538 Tue 2027-06-22
  ["NUTTY", "SALT", "GEM"], // #539 Wed 2027-06-23
  ["ARROW", "SOFA", "FAR"], // #540 Thu 2027-06-24
  ["COVE", "GALE", "HALO"], // #541 Fri 2027-06-25
  ["OIL", "GAB", "HUM", "LOW"], // #542 Sat 2027-06-26
  ["BRISKET", "ORBIT"], // #543 Sun 2027-06-27
  ["PANTHER", "PLANK"], // #544 Mon 2027-06-28
  ["SUNBEAM", "TIARA"], // #545 Tue 2027-06-29
  ["COMET", "JINX", "SET"], // #546 Wed 2027-06-30
  ["SKIFF", "SINK", "SAD"], // #547 Thu 2027-07-01
  ["PLOW", "MULE", "WOOD"], // #548 Fri 2027-07-02
  ["BOO", "SIT", "WIZ", "JUT"], // #549 Sat 2027-07-03
  ["HORNET", "PULLEY"], // #550 Sun 2027-07-04
  ["ORIGAMI", "FAIRY"], // #551 Mon 2027-07-05
  ["YOGURT", "LAUREL"], // #552 Tue 2027-07-06
  ["QUILT", "CHIP", "COO"], // #553 Wed 2027-07-07
  ["CHALK", "LAWN", "BUD"], // #554 Thu 2027-07-08
  ["LLAMA", "SILK", "LAD"], // #555 Fri 2027-07-09
  ["CRY", "DAY", "MIX", "EBB"], // #556 Sat 2027-07-10
  ["KERNEL", "BRANCH"], // #557 Sun 2027-07-11
  ["PANCAKE", "TULIP"], // #558 Mon 2027-07-12
  ["MELODY", "MARMOT"], // #559 Tue 2027-07-13
  ["COBRA", "WASP", "PEP"], // #560 Wed 2027-07-14
  ["SCOUT", "WAVY", "ELM"], // #561 Thu 2027-07-15
  ["CHIVE", "HUSK", "GAP"], // #562 Fri 2027-07-16
  ["MOM", "SEW", "MOW", "FIB"], // #563 Sat 2027-07-17
  ["ELIXIR", "COYOTE"], // #564 Sun 2027-07-18
  ["BAMBOO", "RAPIDS"], // #565 Mon 2027-07-19
  ["BEEHIVE", "SCONE"], // #566 Tue 2027-07-20
  ["IVORY", "LARK", "GOO"], // #567 Wed 2027-07-21
  ["POPPY", "WHIP", "TIP"], // #568 Thu 2027-07-22
  ["POEM", "ARCH", "PEAK"], // #569 Fri 2027-07-23
  ["PEW", "AWL", "ARC", "PAW"], // #570 Sat 2027-07-24
  ["MUTTON", "CONVOY"], // #571 Sun 2027-07-25
  ["JACKPOT", "EBONY"], // #572 Mon 2027-07-26
  ["BUNKER", "JOYFUL"], // #573 Tue 2027-07-27
  ["FUDGE", "OXEN", "KEG"], // #574 Wed 2027-07-28
  ["BEECH", "CAMP", "HOP"], // #575 Thu 2027-07-29
  ["TABLE", "BALL", "TOT"], // #576 Fri 2027-07-30
  ["FUN", "WAY", "ZAG", "LAW"], // #577 Sat 2027-07-31
  ["SPHINX", "PAPAYA"], // #578 Sun 2027-08-01
  ["HICKORY", "RODEO"], // #579 Mon 2027-08-02
  ["POODLE", "HUMBUG"], // #580 Tue 2027-08-03
  ["SWING", "HOOF", "YUM"], // #581 Wed 2027-08-04
  ["GOWN", "LILY", "LAMB"], // #582 Thu 2027-08-05
  ["HINGE", "CONE", "YES"], // #583 Fri 2027-08-06
  ["FLU", "RAT", "SAX", "HOT"], // #584 Sat 2027-08-07
  ["ALMOND", "FONDUE"], // #585 Sun 2027-08-08
  ["MONSOON", "ZIPPY"], // #586 Mon 2027-08-09
  ["JAYWALK", "POLKA"], // #587 Tue 2027-08-10
  ["SHEEP", "MAZE", "END"], // #588 Wed 2027-08-11
  ["LOOM", "PIPE", "BIRD"], // #589 Thu 2027-08-12
  ["GOOFY", "DUNE", "TAX"], // #590 Fri 2027-08-13
  ["NEW", "IMP", "GUY", "PUN"], // #591 Sat 2027-08-14
  ["SIERRA", "BISTRO"], // #592 Sun 2027-08-15
  ["ABACUS", "IMPALA"], // #593 Mon 2027-08-16
  ["BUZZARD", "CHARM"], // #594 Tue 2027-08-17
  ["CURRY", "CHIN", "ODD"], // #595 Wed 2027-08-18
  ["PERCH", "DOLL", "JIG"], // #596 Thu 2027-08-19
  ["BIKE", "TWIG", "CURL"], // #597 Fri 2027-08-20
  ["DRY", "COY", "OAR", "BOG"], // #598 Sat 2027-08-21
  ["CUPCAKE", "BUNNY"], // #599 Sun 2027-08-22
  ["BAGPIPE", "FERRY"], // #600 Mon 2027-08-23
  ["FIREFLY", "KEBAB"], // #601 Tue 2027-08-24
  ["LEMON", "LAZY", "LOW"], // #602 Wed 2027-08-25
  ["OASIS", "BOOK", "GAS"], // #603 Thu 2027-08-26
  ["HERON", "JEEP", "PAL"], // #604 Fri 2027-08-27
  ["SOD", "BAR", "AIR", "BYE"], // #605 Sat 2027-08-28
  ["JAGUAR", "PICKLE"], // #606 Sun 2027-08-29
  ["ECLIPSE", "JELLY"], // #607 Mon 2027-08-30
  ["UKULELE", "BARGE"], // #608 Tue 2027-08-31
  ["BOXER", "MULE", "PET"], // #609 Wed 2027-09-01
  ["WOOD", "BEAK", "OVAL"], // #610 Thu 2027-09-02
  ["HAZY", "CART", "MOSS"], // #611 Fri 2027-09-03
  ["DUO", "BUY", "TUG", "HOE"], // #612 Sat 2027-09-04
  ["BELFRY", "PODIUM"], // #613 Sun 2027-09-05
  ["GAZEBO", "CIRCUS"], // #614 Mon 2027-09-06
  ["VULTURE", "DRAKE"], // #615 Tue 2027-09-07
  ["KOALA", "TOGA", "DAY"], // #616 Wed 2027-09-08
  ["HAZEL", "BEAM", "HUM"], // #617 Thu 2027-09-09
  ["STOOL", "SNOW", "EWE"], // #618 Fri 2027-09-10
  ["POT", "WRY", "TRY", "OIL"], // #619 Sat 2027-09-11
  ["WHISKER", "GOURD"], // #620 Sun 2027-09-12
  ["SARDINE", "WHISK"], // #621 Mon 2027-09-13
  ["DESSERT", "GROVE"], // #622 Tue 2027-09-14
  ["JUICE", "CHIP", "SEW"], // #623 Wed 2027-09-15
  ["PANSY", "FLAX", "OWN"], // #624 Thu 2027-09-16
  ["STORK", "WALL", "OUT"], // #625 Fri 2027-09-17
  ["BOO", "FIB", "POP", "ONE"], // #626 Sat 2027-09-18
  ["PIGLET", "NAPKIN"], // #627 Sun 2027-09-19
  ["ROOKIE", "SQUIRT"], // #628 Mon 2027-09-20
  ["DRIZZLE", "HOUND"], // #629 Tue 2027-09-21
  ["RHINO", "TOWN", "JUG"], // #630 Wed 2027-09-22
  ["QUAIL", "HERB", "ASH"], // #631 Thu 2027-09-23
  ["YODEL", "DEER", "HOG"], // #632 Fri 2027-09-24
  ["TAG", "GAB", "LID", "BUS"], // #633 Sat 2027-09-25
  ["TABLET", "STUDIO"], // #634 Sun 2027-09-26
  ["WALLABY", "LATCH"], // #635 Mon 2027-09-27
  ["LETTUCE", "SHELF"], // #636 Tue 2027-09-28
  ["DONUT", "TRAY", "INN"], // #637 Wed 2027-09-29
  ["JAZZY", "LOFT", "YAP"], // #638 Thu 2027-09-30
  ["BLIMP", "DIME", "RUB"], // #639 Fri 2027-10-01
  ["ARK", "WAY", "COG", "LAD"], // #640 Sat 2027-10-02
  ["VANILLA", "LINEN"], // #641 Sun 2027-10-03
  ["HAMMER", "WEASEL"], // #642 Mon 2027-10-04
  ["DOLPHIN", "PEONY"], // #643 Tue 2027-10-05
  ["WHALE", "MILL", "ARM"], // #644 Wed 2027-10-06
  ["YUCCA", "WICK", "RIP"], // #645 Thu 2027-10-07
  ["LADLE", "SILK", "PRO"], // #646 Fri 2027-10-08
  ["ZIG", "PAW", "OAT", "SIT"], // #647 Sat 2027-10-09
  ["RAVINE", "HICCUP"], // #648 Sun 2027-10-10
  ["SPARROW", "CARGO"], // #649 Mon 2027-10-11
  ["CRUMPET", "NUTTY"], // #650 Tue 2027-10-12
  ["DRILL", "POEM", "TWO"], // #651 Wed 2027-10-13
];
